version: "3"
services:
  ri_server:
    image: cjrutherford/ri_server:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "3200:3200"
    networks:
      - web
networks:
  web:
